# Generated by Django 2.1.3 on 2019-05-23 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': '用户描述'},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='aboutme',
            field=models.TextField(blank=True, verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(blank=True, max_length=100, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profession',
            field=models.CharField(blank=True, max_length=100, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='school',
            field=models.CharField(blank=True, max_length=100, verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='电化号码'),
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='用户信息',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='UserProfile',
        ),
    ]
